name: Python package

on:
  push:
    branches: [ master, v3 ]
  pull_request:
    branches: [ master, v3 ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Set up uv
      uses: hynek/setup-cached-uv@v2
      with:
        cache-dependency-path: uv.lock
    - name: Pin Python version
      run: uv python pin ${{ matrix.python-version }}
    - name: Sync dependencies
      run: uv sync
    - name: Lint check
      run: uv run ruff check
    - name: Check formatting
      run: uv run ruff format --check

  test:
    runs-on: ubuntu-latest
    environment: tests
    env:
      OPENREVIEW_TOKEN: ${{ secrets.OPENREVIEW_TOKEN }}
    strategy:
      matrix:
        settings:
        - python: '3.13'
          coverage: false
    steps:
    - name: Set month outputs
      id: month
      run: echo "month=$(date +%m)" >> $GITHUB_OUTPUT

    - name: Check out the code
      uses: actions/checkout@v3
    - name: Set up uv
      uses: hynek/setup-cached-uv@v2
      with:
        cache-dependency-path: uv.lock

    - name: Restore tests cache
      uses: actions/cache/restore@v5
      id: restore-cache
      with:
        path: ./tests/cache/
        # Reset the completely every month
        key: tests-cache-${{ steps.month.outputs.month }}

    - name: List tests cache
      continue-on-error: true
      run: ls -lR tests/cache/

    - name: Install Podman
      uses: gacts/install-podman@v1.1.1
    - name: Install and set up Hatch
      run: |
        uv tool install hatch
        echo "HATCH_UV=$(which uv)" >>$GITHUB_ENV
    - name: Pin Python version
      run: uv python pin ${{ matrix.settings.python }}
    - name: Sync dependencies
      run: uv sync
    - name: Setup mongo
      run: hatch run mongo:start
    - name: Test with pytest
      if: ${{ !matrix.settings.coverage }}
      run: uv run pytest tests/
    - name: Test with pytest and coverage
      if: ${{ matrix.settings.coverage }}
      run: uv run pytest --cov=src --cov-report term-missing tests/
    - name: Verify coverage
      if: ${{ matrix.settings.coverage }}
      run: uv run coverage report | tail -1 | egrep "TOTAL +[0-9]+ +0 +100%"
    - name: Stop mongo
      if: always()
      run: hatch run mongo:stop
    
    - name: Store tests cache
      if: always()
      uses: actions/cache/save@v5
      with:
        path: ./tests/cache/
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
